##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-icon-theme
    - clang
    - clang-tools
    - expect #required for unbuffer
    - gawk
    - git
    - make
    - libxml-simple-perl

build_scripts:
  - ./make-scanbuild
  - ./exit-warning
